name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          retain_days: 2
          keep_minimum_runs: 5
