name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
#  schedule:
#    - cron: '*/10 * * * *'

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup DB schema (if missing)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: npx ts-node src/setup-db.ts

      - name: Run Playwright tests
        env:
          STUDIP_URL: https://studip.hs-schmalkalden.de
          STUDIP_USER: ${{ secrets.STUDIP_USER }}
          STUDIP_PASS: ${{ secrets.STUDIP_PASS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: npx playwright test
